# Reference: https://github.com/marketplace/actions/setup-node-js-environment 

name: Truffle Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup NodeJS 16
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package.json') }}
        restore-keys: npm-

    - name: Install dependencies
      run: npm install

    - name: Run Truffle Test
      run: |
        npm run ganache 2>/dev/null >/dev/null &
        sleep 4
        npm run test
